### ISSUE TITLE
Fanuc LR Mate 200id Support

### ISSUE THREAD

**Issue by jav-solo** [gavanderhoorn/fanuc_ros_cgio#1]
I cannot seem to find an option on the TP for R626 (Web Server), I do have the Karel option installed, is there a way to make this work? I have Karel, Ethernet/IP, and User Socket Messaging (R648).

**Comment by jav-solo** [comment]
What I am trying to do is have access to the robot I/O to control a custom gripper. Thanks for your help.

**Comment by gavanderhoorn** [comment]
If you already have Ethernet/IP, I wouldn't bother with the scripts in this repository.

Using a real fieldbus is always preferable in my opinion.

I would be really surprised if you don't have the web server option on your controller btw: I'll assume you have an R-30iB controller, and it should be almost installed by default on those.

**Comment by gavanderhoorn** [comment]
Easiest way to check whether you have the option is to just try and open `http://ip.of.your.robot/` in a web browser.

if that works, you probably have the option.

**Comment by jav-solo** [comment]
Thanks for the quick response, I am using a R-30iB Mate Controller. Excuse my ignorance but, how would I go about using a fieldbus? 

Also, when I try and run the makefile included, I am getting a few errors.
```
make: ktrans.exe: Command not found
make: *** [ros_cgio.pc] Error 127
```

**Comment by jav-solo** [comment]
> Easiest way to check whether you have the option is to just try and open http://ip.of.your.robot/ in a web browser.
>if that works, you probably have the option.

I have verified that I do have the option then.

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
> how would I go about using a fieldbus?

in the case of Ethernet/IP, you can just use a regular ethernet network together with a library that implements the scanner functionality. Something like [pycomm](https://pypi.org/project/pycomm) or [pjkundert/cpppo](https://github.com/pjkundert/cpppo). Alternatively you could look at [ros-drivers/odva_ethernetip](https://github.com/ros-drivers/odva_ethernetip) but that is rather underdocumented at the moment.

At this point you have access to the raw IO on your robot controller, but no ROS API for it. That would be something you'd have to add yourself, or, if you don't want/need that, just keep working with whatever library you're using.

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
> Also, when I try and run the makefile included, I am getting a few errors.
> ```
> make: ktrans.exe: Command not found
> make: *** [ros_cgio.pc] Error 127
> ```

This just means that you don't have `ktrans.exe` on your Windows `PATH`.

You can either add the directory containing that to your `PATH` environment variable, or update the `CC` line in `Makefile` to point to the correct location (probably something like `C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe`).

I'll see if I can compile the program for `V7.70` and `V8.30`, but don't wait for me.

**Comment by jav-solo** [comment]
> This just means that you don't have ktrans.exe on your Windows PATH.

I'm using Ubuntu 14.04

**Comment by gavanderhoorn** [comment]
Well then that won't work at all, as all Fanuc tools and utilities only work under Windows.

This is also mentioned in the readme:

> Translate the `ros_cgio.kl` either with Roboguide or with the supplied `Makefile`. The latter will require a compatible version of GNU Make for Windows to be available.

**Comment by jav-solo** [comment]
Ok, I will use a Windows PC to translate the Karel files and load them onto the controller and let you know if it works for me. Thanks again.

**Comment by jav-solo** [comment]
I cannot get nmake to work in my Visual Studio Command Prompt. 

`makefile(3) : fatal error U1001: syntax error : illegal character '?' in macro`
`Stop.`

**Comment by gavanderhoorn** [comment]
The `Makefile` is not compatible with `nmake`. From the readme:

> require a compatible version of GNU Make for Windows

Let's forget about using the `Makefile`. Try the following command (in a Windows `cmd` window, in the directory containing the `.kl` file, on the PC with Roboguide):

```
"C:\Program Files (x86)\Fanuc\WinOLPC\bin\ktrans.exe" ros_cgio.kl /ver V8.30-1
```

If this succeeds, you should now have a `ros_cgio.pc` file.

(use the exact command (copy-paste it): the double quotes are important)

**Comment by jav-solo** [comment]
Unfortunately, I don't have Roboguide. I tried using Cygwin and I received the same error as in Ubuntu.

`make: ktrans.exe: Command not found`
`make: *** [Makefile:28: ros_cgio.pc] Error 127`

**Comment by gavanderhoorn** [comment]
Do you have any Fanuc software available to you?

**Comment by jav-solo** [comment]
Just the original load media for the controller, nothing else.

**Comment by gavanderhoorn** [comment]
Then you can't compile or edit anything.

Without `ktrans.exe`, someone else will have to compile the Karel program for you.

As I mentioned earlier, I may be able to do that later, but I can't say when.

**Comment by gavanderhoorn** [comment]
If you have option `R553`, you may want to take a look at gavanderhoorn/fanuc_driver_exp#12. That would be another way to interface with the controller's IO, albeit somewhat more involved.

**Comment by jav-solo** [comment]
Oh, I see. I guess I misunderstood the process, thanks for your help.

**Comment by gavanderhoorn** [comment]
Please see [fanuc_ros_cgio_pcode.zip](https://github.com/gavanderhoorn/fanuc_ros_cgio/files/2055256/fanuc_ros_cgio_pcode.zip).

I've compiled the program twice: once for `V7.70-1` and once for `V8.30-1` controllers. You'll most likely need the `V8.30-1` version.

Don't forget to remove the version nr from the filename before copying it to the controller.

**Comment by jav-solo** [comment]
Got it, thank you very much. I loaded it onto the controller. There wasn't any "nr" in the filename it was just ros_cgio_830.pc When I run the program however I see this in the terminal: 

```
curl -s http://192.168.1.4/KAREL/ros_cgio?io_op=write&io_type=9&io_idx=1&io_val=1
[1] 3533
[2] 3534
[3] 3535
```

```
"<HTML><BODY><P><H2>HTTP/1.0 401 Unauthorized
</H2></BODY></HTML>"
[1]   Done                    curl -s http://192.168.1.4/KAREL/ros_cgio?io_op=write
[2]-  Done                    io_type=9
[3]+  Done                    io_idx=1
```

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
>  There wasn't any "nr" in the filename it was just ros_cgio_830.pc

`830` is a nr, isn't it? `nr` is short for `number`.

As to the rest: please follow *all* instructions in the readme. Particularly those in section [Requirements](https://github.com/gavanderhoorn/fanuc_ros_cgio#requirements).

Also: be sure to keep the double quotes around the URL. You need to be careful with this, as the quotes are important.

**Comment by jav-solo** [comment]
I got it, I just needed to unlock the web authentication. The program you provided works great, thank you. One last question, could you tell me how I would integrate this into my workspace which is in C++? I just want to be able to access the IO through my code.

**Comment by jav-solo** [comment]
Also, I did not remove the _830 but it still works. Should I rename it?

**Comment by gavanderhoorn** [comment]
@javiersolorzano wrote:
> One last question, could you tell me how I would integrate this into my workspace which is in C++? I just want to be able to access the IO through my code.

you'll either have to write a client using something like `curl` (ie: the C++ lib), or use the Python wrapper available in [gavanderhoorn/fanuc_ros_cgio_py](https://github.com/gavanderhoorn/fanuc_ros_cgio_py). The latter could easily be wrapped in a ROS API (ie: read/write ROS services), which you can then use from any other ROS node.

**Comment by gavanderhoorn** [comment]
And yes, I would recommend you rename it.

**Comment by gavanderhoorn** [comment]
As it seems you got things to work, I'm closing this.

Please carefully read any provided instructions in the future. They are there for a reason.

We're always happy to help, but the instructions are there to save time: both yours (you don't have to wait on assistance) as well as ours.

**Comment by jav-solo** [comment]
Thanks again for your help!
